apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elevenlabs

resources:
  - namespace.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - gpu-worker-deployment.yaml
  - ingress.yaml

commonLabels:
  app: elevenlabs
  managed-by: kustomize
